- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "component: agents"
  color: "fbca04"
  description: "Agent-related functionality and features"

- name: "component: infra"
  color: "7057ff"
  description: "Infrastructure and system architecture"

- name: "component: ui"
  color: "6f42c1"
  description: "User interface and frontend components"

- name: "core-categories"
  color: "fd7e14"
  description: "Fundamental agent classification and organization system"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "epic"
  color: "6f42c1"
  description: "High-level tracking issue that encompasses multiple related features or tasks"

- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

- name: "priority: high"
  color: "d73a4a"
  description: "Urgent or blocking issues"

- name: "priority: low"
  color: "0e8a16"
  description: "Nice to have, can wait"

- name: "priority: medium"
  color: "fbca04"
  description: "Important but not urgent"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "showcase-agents"
  color: "0e8a16"
  description: "Agent showcase features and implementations"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
