---
name: "📚 Documentation"
description: Suggest improvements to our documentation
title: "[Docs]: "
labels: ["type: documentation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs to be updated?
      options:
        - README
        - Contributing Guidelines
        - Code of Conduct
        - API Documentation
        - Installation Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What's wrong or missing in the current documentation?
      placeholder: Please describe the issues you've found...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Changes
      description: How should we improve the documentation?
      placeholder: Please describe your suggested improvements...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation improvement here.
